version: '3.8'

services:
  # Spring Boot 应用
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGO_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-password}
      # 使用本地 MongoDB 的连接字符串
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/dutch-vocab
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - dutch-vocab-network

  # MongoDB 数据库（本地开发用）
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=dutch-vocab
    networks:
      - dutch-vocab-network

networks:
  dutch-vocab-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local